# Generated by Django 3.0.6 on 2020-08-27 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(help_text='Enter your full name', max_length=20)),
                ('gmail', models.EmailField(blank=True, help_text='optional', max_length=254, validators=[django.core.validators.EmailValidator])),
                ('phoneNumber', models.IntegerField(help_text='this num will be used to access your account', primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(help_text='Enter your address', max_length=100)),
                ('town', models.CharField(help_text='Enter your city/town name', max_length=20)),
                ('state', models.CharField(help_text='Enter your state', max_length=20)),
                ('password', models.CharField(help_text='Enter strong Password', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
