# Generated by Django 3.0.6 on 2020-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='AP', help_text='Enter your state', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='town',
            field=models.CharField(default='PLMR', help_text='Enter your city/town name', max_length=20),
            preserve_default=False,
        ),
    ]
