# Generated by Django 3.0.6 on 2020-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.CharField(default='plumbing', help_text='Enter the services you provide', max_length=100),
            preserve_default=False,
        ),
    ]
