# Generated by Django 3.0.6 on 2020-07-14 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arya', '0002_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(help_text='Enter your full name', max_length=20)),
                ('gmail', models.EmailField(blank=True, help_text='optional', max_length=254, validators=[django.core.validators.EmailValidator])),
                ('phoneNumber', models.IntegerField(help_text='This number will be used to access your account', primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(help_text='Enter your complete address', max_length=20)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffMembers', to='arya.Manager')),
            ],
        ),
    ]
