# Generated by Django 3.0.6 on 2020-07-18 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arya', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='state',
            field=models.CharField(default='AP', help_text='Enter your state', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='town',
            field=models.CharField(default='plmr', help_text='Enter your city/town name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='availableFrom',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='availableTill',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=1234, help_text='Enter strong Password', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='state',
            field=models.CharField(default='AP', help_text='Enter your state', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='town',
            field=models.CharField(default='PLMR', help_text='Enter your city/town name', max_length=20),
            preserve_default=False,
        ),
    ]
